website/config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'searchrios#display'
  get 'profile' => 'profile#display'
  get 'home' => 'home#homepage'
  get 'contactos' => 'about#about'
  get 'documentos' => 'documentos_relacionados#documentos'
  get 'distritos' => 'concelho#getDistritos'
  get 'concelhos' => 'concelho#getConcelhosFromDistrito'
  get 'limpeza/new' => 'limpeza#new'
  get 'limpeza/info' => 'limpeza#info'
  get 'limpeza/:id' => 'limpeza#show', :as => :limpeza
  delete 'limpeza/:id' => 'limpeza#destroy'
  get 'respostas' => 'limpeza#getRespostas'

  get 'adminpanel' => 'admin#index' #users index
  get 'adminpanel/form_irrs' => 'admin#form_irrs', :as => :index_form_irrs
  get 'adminpanel/sos_rios' => 'admin#reports', :as => :index_reports
  get 'adminpanel/rotas' => 'admin#rotas', :as => :index_rotas
  get 'adminpanel/trips' => 'admin#trips', :as => :index_trips
  get 'adminpanel/guardarios' => 'admin#guardarios', :as => :index_guardarios
  get "adminpanel/limpezas", :to => 'admin#limpezas', :as => :index_limpezas

  post 'submitProblemasAction' => 'limpeza#submitProblemas'
  post 'changePermissions' => 'users#updatepermissions'

  post 'rota_point_image' => 'rota_point_image#create'
  delete 'rota_point_image/:id' => 'rota_point_image#destroy'

  post 'trip_point_image' => 'trip_image#create'
  delete 'trip_point_image/:id' => 'trip_image#destroy'

  get 'meusguardarios' => 'guardarios#getMine'

  #info pages
  get 'reabilitacao/info' => 'reabilitacaos#info'
  get 'form_irr/info' => 'form_irrs#info'
  get 'report/info' => 'reports#info'
  get 'lab_rios/info' => 'lab_rios#info'
  get 'participacao_publica/info' => 'participacao_publica#info'
  get 'projetos/info' => 'projetos#info'

  #show all
  get 'form_irrs/all' => 'form_irrs#all'
  get 'trips/all' => 'trips#all'

  get 'rio/irrrange' => 'rio#getIRRrange'
  get 'rio/:id' => 'rio#show', as: :rio, :id => /.*/

  get 'form_irrs/img/:caminho' => 'form_irrs#retrieveImage', :caminho => /.*/

  resources :form_irr_image
  resources :reabilitacaos
  resources :guardarios, only: [:index, :show, :new, :create, :destroy]
  resources :reports, only: [:index, :show, :new, :create, :destroy]
  resources :form_irrs
  resources :trip_points
  resources :trips
  resources :routes
  resources :rotas

  patch 'validate_form_irrs/:id' => 'form_irrs#validate', :as => :validate_form_irr
  get 'validate_form_irrs' => 'form_irrs#validate_index'

  devise_for :users, :controllers => {registrations: 'registrations'}

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#homepage'

  # rotas da API, usadas pela app
  namespace :api do
    namespace :v1 do
      resources :problems
      resources :services
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
    end
    namespace :v2 do
      post "/form_irrs", :to => 'form_irrs#create'
      get "/form_irrs", :to => 'form_irrs#getMyForms'
      get "/form_irrs/:id", :to => 'form_irrs#get'
      put "/form_irrs/:id", :to => 'form_irrs#update'
      delete "/form_irrs/:id", :to => 'form_irrs#destroy'

      post "/image", :to => 'image#create'

      post "/guardarios", :to => 'guardarios#create'
      get "/guardarios/:id", :to => 'guardarios#get'
      get "/guardarios", :to => 'guardarios#recent'

      post "/reports", :to => 'reports#create'
      get "/reports", :to => 'reports#index'
      get "/reports/:id", :to => 'reports#get'

      get "/limpezas/:opcao", :to => 'limpezas#getRespostas', :opcao => /.*/
      post "/limpezas", :to => 'limpezas#submitProblemas'

      get "/users", :to => 'users#getUser'
      delete "/users", :to => 'users#destroy'
      put "/users", :to => 'users#update'

	    get "/routes", :to => 'routes#index'
      get "/routes/:id", :to => 'routes#show'

      get "/distritos", :to => 'localidades#getDistritos'
      get "/distritos/:distrito", :to => 'localidades#getConcelhos'
    end
  end

  #web views for app
  get 'rios_mapa_webview' => 'application_web_view#showMapa'
end

website/app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :trip_points, dependent: :destroy
end

website/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :custom_auth!

  def custom_auth!
    if authenticate_user!
      @permissoes = current_user.permissoes
      if current_user.permissoes > 1
        return true
      else
        render 'common/noaccess'
      end
    else
      render 'common/noaccess'
    end
  end


  # Mostra o index de trips, apresentando uma lista com os trips efectuados pelo próprio user,
  # ordenados por ordem decrescente de data de actualização, e divididos por páginas,
  # com 10 trips cada.
  # GET /trips
  def index
    @all = false
    @trips = current_user.trips.paginate(:page => params[:page], :per_page => 10).order('updated_at DESC')
  end

  # Index de trips com todas as trips, para utilizadores com permissoes > 4.
  # lista com TODAS as trips, divididas por páginas de 10 trips, ordenadas por ordem decrescente.
  def all
    if current_user.permissoes > 4
      @all = true
      @trips = Trip.all.paginate(:page => params[:page], :per_page => 10).order('updated_at DESC')
      render 'index'
    else
      render 'common/noaccess'
    end
  end

  # Página que mostra uma trip. Mostra mapa com os vários pontos, e informação relativa a cada ponto.
  # GET /trips/1
  # GET /trips/1.json
  def show
    @points = @trip.trip_points
  end

  # Render de página para criar um trip.
  # GET /trips/new
  def new
    @trip = Trip.new
    @edit = false;
  end

  # Render de página para edição de uma trip, com possibilidade de adicionar pontos à mesma.
  # GET /trips/1/edit
  def edit
    if( @trip.user_id != current_user.id)
      render 'common/noaccess'
    else
      @edit = true;
      @points = @trip.trip_points
    end
  end

  # Action de criação de trip (só trip, sem pontos)
  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params)
    @trip.user_id = current_user.id
    if @trip.save
      redirect_to edit_trip_path(@trip)
    else

    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # Action para apagar a trip.
  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:idRio, :nomeRio)
    end
end

website/app/helpers/trips_helper.rb
module TripsHelper
end

website/app/views/trips/_form.html.erb
<%= simple_form_for @trip, html: { multipart: true, :"data-edit" => @edit, :"data-trip-id" => @trip.id } do |f| %>
    <% #= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %>
    <%= f.error_notification %>

    <div class="form-inputs">

      <div class="form-group container">

        <div id="rio-nome" class="rio-info form-inline">
          <div class="row">
            <div class="thumbnail">

              <div class="row">
                <div class="col-md-6 col-xs-12">
                  <%= f.label :idRio, "Código do rio:" %>
                  <%= f.text_field :idRio, :id => 'codigo-rio', :class => 'text_field form-control',
                                   :readonly => true, :placeholder => "Clique em cima do rio para selecionar", :required => true %>
                </div>
                <div class="col-md-6 col-xs-12">
                  <%= f.label :nomeRio, "Nome do rio:" %>
                  <%= f.text_field :nomeRio, :id => 'nome-rio', :class => 'text_field form-control',
                                   :readonly => true, :placeholder => "Clique em cima do rio para selecionar", :required => true %>
                </div>
                <% if @edit %>
                    <div class="col-md-6 col-xs-12">
                      <%= label_tag 'created-at' do %>
                          Iniciada em:
                      <% end %>
                      <%= text_field_tag 'created-at', @trip.created_at.strftime("%d/%m/%Y - %H:%M"), {:class => 'text_field form-control',  :readonly => true }%>
                    </div>
                    <div class="col-md-6 col-xs-12">
                      <%= label_tag 'nome-user' do %>
                          Criada por:
                      <% end %>
                      <%= text_field_tag 'nome-user', current_user.nome, {:class => 'text_field form-control',  :readonly => true }%>
                    </div>
                <% end %>
              </div>
              <% if !@edit %>
                <%= render 'mapa/mapa' %>
              <% end %>
            </div>
          </div>
        </div>

        </div>

      <!--<div class="form-actions">
      </div>-->
    </div>
    <% if !@edit %>
        <%= f.button :submit, 'Iniciar Trip' %>
    <% end %>
<% end %>
<% if @edit %>
    <div class="row">
      <div class="col-xs-12">
        <h2>Pontos da rota</h2>
        <p>Pode adicionar um ponto à trip clicando no mapa, ou utilizando as funcionalidades de localização GPS do seu dispositivo, clicando no botão indicado. Para remover o ponto, basta clicar no marcador referente ao mesmo no mapa.</p>
      </div>

      <div class="col-xs-12" id="map-wrapper">
        <div id="add-trip-points-map" class="col-xs-12"></div>

        <div id="over-map-container">
          <button id="add-gps-point-trip" class="btn btn-primary" disabled="disabled">Adicionar Ponto GPS</button>
        </div>
      </div>

      <div id="points-info" style="display: none">
        <% @points.each do |p| %>
          <div class="point-info" data-point-id="<%= p.id%>" data-point-lat="<%= p.lat%>" data-point-lon="<%= p.lon%>" data-point-descricao="<%= p.descricao%>"></div>
        <% end %>
      </div>

      <div id="left-panel-forms" class="col-xs-12">
        <h3>Informações sobre os pontos:</h3>
        <div id="form-current-marker" class="thumbnail">
          <div class="row">
            <div class="col-md-4">
              Nome:<input id="point-nome" type="text-field" name="nome" class="form-control empty-this" value="" disabled="disabled"/>
            </div>
            <div class="col-md-4">
              Latitude:<input id="point-lat" type="text-field" name="lat" class="form-control" readonly="true" value="Nenhum ponto selecionado..."/>
            </div>
            <div class="col-md-4">
              Longitude:<input id="point-lon" type="text-field" name="lon" class="form-control" readonly="true" value="Nenhum ponto selecionado..."/>
            </div>
            <div class="col-md-12">
              <textarea id="point-text" type="text-field" name="descricao" class="form-control empty-this"  rows="4" placeholder="Insira uma descrição" disabled="disabled"></textarea>
            </div>
          </div>
          <div class="form-group container">
            <div id="img-filenames"></div>
            <div id="trip-point-imgs">
              <button id="btn-add-img-trip-point" class="btn btn-primary" type="button" disabled="disabled"> Adicionar imagens </button>
              <%= file_field_tag "images[]", type: :file, multiple: true, accept: 'image/png,image/gif,image/jpeg', style: 'display:none', id: "trip-point-img-input" %>
            </div>
          </div>
          <button id="add-point-btn" class="btn btn-success" disabled="disabled">Adicionar Ponto</button>
        </div>
      </div>

    </div>
<% end %>

<!--<button id="submit-rota" class="btn btn-primary">Guardar Rota</button>-->

website/app/views/trips/edit.html.erb
<%= render 'common/header' %>

<%= stylesheet_link_tag "trips" %>
<%= stylesheet_link_tag "external/jquery-ui.min.css" %>

</head>

<body>

<%= render 'common/navbar' %>

<div class="container">
  <h1>Adicionar Pontos ao Trip no/a <%= @trip.nomeRio %></h1>
  <%= render 'form' %>

  <%= link_to 'Mostrar', @trip %> |
  <%= link_to 'Voltar atrás', trips_path %>

</div>

<%= render 'common/footer' %>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<%= javascript_include_tag 'trips' %>
<%= javascript_include_tag "trip_image" %>

website/app/views/trips/index.html.erb
<%= render 'common/header' %>
</head>
<body>
<%= render 'common/navbar' %>

<div class="container">
  <% if @all %>
      <h1>Todas as Trips</h1>
  <% else %>
      <h1>Minhas Trips <%= link_to "Nova Trip", new_trip_path, class: "btn btn-primary" %></h1>
  <% end %>

  <div class="table-responsive">
    <table class="table table-hover table-striped">
      <tr>
        <th>Id</th>
        <th>Rio</th>
        <th>Criado em</th>
        <th>Editado em</th>
        <th>Ver</th>
        <th>Editar</th>
        <th>Apagar</th>
      </tr>
      <% @trips.each do |trip| %>
          <tr>
            <td><%= trip.id %></td>
            <td><%= link_to trip.nomeRio, trip_path(trip.idRio) %></td>
            <td><%= trip.created_at.strftime("%d/%m/%Y - %H:%M") %></td>
            <td><%= trip.updated_at.strftime("%d/%m/%Y - %H:%M") %></td>
            <td><%= link_to 'Ver', trip_path(trip) %></td>
            <td><%= link_to 'Editar', edit_trip_path(trip) %></td>
            <td><%= link_to 'Apagar', trip_path(trip), method: :delete, data: {:confirm => "Tem a certeza que quer apagar a trip?"} %></td>
          </tr>
      <% end %>
    </table>
  </div>
  <%= will_paginate @trips, :previous_label => 'Anterior', :next_label => 'Seguinte' %>
</div>

<%= render 'common/footer' %>

website/app/views/trips/new.html.erb
<%= render 'common/header' %>

<%= stylesheet_link_tag "trips" %>
<%= stylesheet_link_tag "external/jquery-ui.min.css" %>

</head>

<body>

<%= render 'common/navbar' %>

<div class="container">
  <h1>Nova Trip</h1>
  <%= render 'form' %>

  <%= link_to 'Voltar atrás', trips_path %>
</div>

<%= render 'common/footer' %>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<%= javascript_include_tag 'trips' %>

website/app/views/trips/noaccess.html.erb
<%= render 'common/header' %>
</head>
<body>

<%= render 'common/navbar' %>
<div class="container">

  <h1> Não tem permissões para aceder a esta página...</h1>

  <%= link_to 'Voltar para as minhas Trips', trips_path %>
</div>

<%= render 'common/footer' %>

website/app/views/trips/show.html.erb
<%= render 'common/header' %>

<%= stylesheet_link_tag "trips" %>
<%= stylesheet_link_tag "external/jquery-ui.min.css" %>

</head>

<body>

<%= render 'common/navbar' %>

<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Trip no/a <%= @trip.nomeRio %></h1>

  <div class="form-inputs">

    <div class="form-group container">
      <div id="rio-nome" class="rio-info form-inline">
        <div class="row">
          <div class="thumbnail">

            <div class="row">
              <div class="col-md-6 col-xs-12">
                <%= label_tag 'codigo-rio' do %>
                    Código do rio:
                <% end %>
                <%= text_field_tag 'codigo-rio', @trip.idRio, {:class => 'text_field form-control',  :readonly => true }%>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= label_tag 'nome-rio' do %>
                    Nome do rio:
                <% end %>
                <%= text_field_tag 'nome-rio', @trip.nomeRio, {:class => 'text_field form-control',  :readonly => true}%>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= label_tag 'created-at' do %>
                    Iniciada em:
                <% end %>
                <%= text_field_tag 'created-at', @trip.created_at.strftime("%d/%m/%Y - %H:%M"), {:class => 'text_field form-control',  :readonly => true }%>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= label_tag 'nome-user' do %>
                    Criada por:
                <% end %>
                <%= text_field_tag 'nome-user', current_user.nome, {:class => 'text_field form-control',  :readonly => true }%>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!--<div class="form-actions">
    </div>-->
  </div>

  <div class="row">
    <div class="col-xs-12">
      <h2>Pontos da rota</h2>
      <p>Para ver informações acerca de cada um dos pontos, basta clicar nos mesmos no mapa abaixo.</p>
    </div>

    <div class="col-xs-12" id="map-wrapper">
      <div id="view-trip-points-map" class="col-xs-12"></div>

      <div id="over-map-container">
        <button id="current-location-btn-trip" class="btn btn-primary" >Ir para localização atual</button>
      </div>
    </div>

    <div id="points-info" style="display: none">
      <% @points.each do |p| %>
          <div class="point-info" data-point-id="<%= p.id%>" data-point-lat="<%= p.lat%>" data-point-lon="<%= p.lon%>" data-point-descricao="<%= p.descricao%>"></div>
      <% end %>
    </div>
  </div>

  <%= link_to 'Editar', edit_trip_path(@trip) %> |
  <%= link_to 'Voltar às minhas trips', trips_path %>

  <!-- Modal -->
  <div class="modal fade" id="modal-trip-point-info" tabindex="-1" role="dialog" aria-labelledby="modal-title">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="modal-title">Informação de ponto</h4>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

</div>

<%= render 'common/footer' %>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<%= javascript_include_tag 'trips-show' %>