website/config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'searchrios#display'
  get 'profile' => 'profile#display'
  get 'home' => 'home#homepage'
  get 'contactos' => 'about#about'
  get 'documentos' => 'documentos_relacionados#documentos'
  get 'distritos' => 'concelho#getDistritos'
  get 'concelhos' => 'concelho#getConcelhosFromDistrito'
  get 'limpeza/new' => 'limpeza#new'
  get 'limpeza/info' => 'limpeza#info'
  get 'limpeza/:id' => 'limpeza#show', :as => :limpeza
  delete 'limpeza/:id' => 'limpeza#destroy'
  get 'respostas' => 'limpeza#getRespostas'

  get 'adminpanel' => 'admin#index' #users index
  get 'adminpanel/form_irrs' => 'admin#form_irrs', :as => :index_form_irrs
  get 'adminpanel/sos_rios' => 'admin#reports', :as => :index_reports
  get 'adminpanel/rotas' => 'admin#rotas', :as => :index_rotas
  get 'adminpanel/trips' => 'admin#trips', :as => :index_trips
  get 'adminpanel/guardarios' => 'admin#guardarios', :as => :index_guardarios
  get "adminpanel/limpezas", :to => 'admin#limpezas', :as => :index_limpezas

  post 'submitProblemasAction' => 'limpeza#submitProblemas'
  post 'changePermissions' => 'users#updatepermissions'

  post 'rota_point_image' => 'rota_point_image#create'
  delete 'rota_point_image/:id' => 'rota_point_image#destroy'

  post 'trip_point_image' => 'trip_image#create'
  delete 'trip_point_image/:id' => 'trip_image#destroy'

  get 'meusguardarios' => 'guardarios#getMine'

  #info pages
  get 'reabilitacao/info' => 'reabilitacaos#info'
  get 'form_irr/info' => 'form_irrs#info'
  get 'report/info' => 'reports#info'
  get 'lab_rios/info' => 'lab_rios#info'
  get 'participacao_publica/info' => 'participacao_publica#info'
  get 'projetos/info' => 'projetos#info'

  #show all
  get 'form_irrs/all' => 'form_irrs#all'
  get 'trips/all' => 'trips#all'

  get 'rio/irrrange' => 'rio#getIRRrange'
  get 'rio/:id' => 'rio#show', as: :rio, :id => /.*/

  get 'form_irrs/img/:caminho' => 'form_irrs#retrieveImage', :caminho => /.*/

  resources :form_irr_image
  resources :reabilitacaos
  resources :guardarios, only: [:index, :show, :new, :create, :destroy]
  resources :reports, only: [:index, :show, :new, :create, :destroy]
  resources :form_irrs
  resources :trip_points
  resources :trips
  resources :routes
  resources :rotas

  patch 'validate_form_irrs/:id' => 'form_irrs#validate', :as => :validate_form_irr
  get 'validate_form_irrs' => 'form_irrs#validate_index'

  devise_for :users, :controllers => {registrations: 'registrations'}

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#homepage'

  # rotas da API, usadas pela app
  namespace :api do
    namespace :v1 do
      resources :problems
      resources :services
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
    end
    namespace :v2 do
      post "/form_irrs", :to => 'form_irrs#create'
      get "/form_irrs", :to => 'form_irrs#getMyForms'
      get "/form_irrs/:id", :to => 'form_irrs#get'
      put "/form_irrs/:id", :to => 'form_irrs#update'
      delete "/form_irrs/:id", :to => 'form_irrs#destroy'

      post "/image", :to => 'image#create'

      post "/guardarios", :to => 'guardarios#create'
      get "/guardarios/:id", :to => 'guardarios#get'
      get "/guardarios", :to => 'guardarios#recent'

      post "/reports", :to => 'reports#create'
      get "/reports", :to => 'reports#index'
      get "/reports/:id", :to => 'reports#get'

      get "/limpezas/:opcao", :to => 'limpezas#getRespostas', :opcao => /.*/
      post "/limpezas", :to => 'limpezas#submitProblemas'

      get "/users", :to => 'users#getUser'
      delete "/users", :to => 'users#destroy'
      put "/users", :to => 'users#update'

	    get "/routes", :to => 'routes#index'
      get "/routes/:id", :to => 'routes#show'

      get "/distritos", :to => 'localidades#getDistritos'
      get "/distritos/:distrito", :to => 'localidades#getConcelhos'
    end
  end

  #web views for app
  get 'rios_mapa_webview' => 'application_web_view#showMapa'
end

website/app/views/common/_footer.html.erb
<footer>
  <div id="footer-content">
    <%= link_to 'Documentos ', documentos_path %> | <%= link_to 'Contactos', contactos_path %>
  </div>
</footer>
</body>

<%= javascript_include_tag 'http://www.openlayers.org/api/OpenLayers.js' %>
<%= javascript_include_tag 'http://maps.google.com/maps/api/js?sensor=false' %>
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'external/Chart.min.js' %>
</html>

website/app/views/common/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Rios+ </title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/<%= bootstrap_version %>/css/bootstrap.min.css" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag "application", media: "all" %>

  <%= stylesheet_link_tag "navbar" %>
  <%= stylesheet_link_tag "footer" %>

  <%= csrf_meta_tags %>

website/app/views/common/_navbar.html.erb
<nav id="navbar" class="navbar navbar-default navigationbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>> Rios+ </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? and current_user.permissoes > 1 %>
          <li>
            <div class="dropdown-container">
              <button type="button" class="dropdown-toggle custom-btn" data-toggle="dropdown">
                Formulários IRR <span class="caret"></span>
              </button>
              <ul id="dropdown-ul" class="dropdown-menu" role="menu">
                <li><%= link_to "Novo formulário", new_form_irr_path %></li>
                <li><%= link_to "Meus formulários", form_irrs_path %></li>
                <% if user_signed_in? and current_user.permissoes > 2 %>
                  <li><%= link_to "Formulários não validados", validate_form_irrs_path %></li>
                <% end %>
              </ul>
            </div>
          </li>
        <% end %>

        <li>
          <div class="dropdown-container">
            <button type="button" class="dropdown-toggle custom-btn" data-toggle="dropdown">
              Rios <span class="caret"></span>
            </button>
            <ul id="dropdown-ul" class="dropdown-menu" role="menu">
              <li><%= link_to "Procurar", search_path %></li>
              <li><%= link_to "SOS Rios+", new_report_path %></li>
              <li><%= link_to "Limpeza Rios+", limpeza_new_path %></li>
              <li><%= link_to "Reabilitação Rios+", reabilitacaos_path %></li>
              <li><%= link_to "Rotas Rios+", routes_path %></li>
              <li><%= link_to "Trips Rios+", trips_path %></li>
            </ul>
          </div>
        </li>

        <li>
          <div class="dropdown-container">
            <button type="button" class="dropdown-toggle custom-btn" data-toggle="dropdown">
              Informações <span class="caret"></span>
            </button>
            <ul id="dropdown-ul" class="dropdown-menu" role="menu">
              <li><%= link_to "Formulário IRR", form_irr_info_path %></li>
              <li><%= link_to "SOS Rios+", report_info_path %></li>
              <li><%= link_to "LabRios+", lab_rios_info_path %></li>
              <li><%= link_to "Reabilitação", reabilitacao_info_path %></li>
              <li><%= link_to "Limpeza", limpeza_info_path %></li>
              <li><%= link_to "Projetos", projetos_info_path %></li>
              <li><%= link_to "Participação pública", participacao_publica_info_path %></li>
            </ul>
          </div>
        </li>

        <li>
          <%= link_to image_tag('guardarios_icon.png', class: 'guardarios_icon'), guardarios_path, id: 'guarda-rios-link' %>
        </li>

        <li>
          <div class="dropdown-container">
            <button type="button" class="dropdown-toggle custom-btn" data-toggle="dropdown">
              <%= content_tag(:span, '', class: 'glyphicon glyphicon-user') %><span class="caret"></span>
            </button>
            <ul id="dropdown-ul" class="dropdown-menu" role="menu">
              <% if user_signed_in? %>
                  <li><%= link_to "Perfil", edit_user_registration_path %></li>
                  <li><%= link_to('Logout', destroy_user_session_path, :method => 'delete') %></li>

                  <% if current_user.permissoes == 6 %>
                      <li><%= link_to "Admin panel", adminpanel_path %></li>
                  <% else %>
                  <% end %>
            <% else %>
                  <li><%= link_to('Login', new_user_session_path) %></li>
                  <li><%= link_to('Registar', new_user_registration_path) %></li>
              <% end %>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

website/app/views/common/_sidebar_admin.html.erb
  <!-- Sidebar -->
  <div id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <li id="espaco-brute-force"></li>
      <!--<li class="sidebar-brand">
        <p>Painel de Administração</p>
      </li>-->
      <li>
        <%= link_to 'Gestão de utilizadores', adminpanel_path %>
      </li>
      <li>
        <%= link_to 'Formulários IRR', index_form_irrs_path %>
      </li>
      <li>
        <%= link_to 'SOS Rios', index_reports_path %>
      </li>
      <li>
        <%= link_to 'Rotas Rios', index_rotas_path %>
      </li>
      <li>
        <%= link_to 'Trips', index_trips_path %>
      </li>
      <li>
        <%= link_to 'Guardarios', index_guardarios_path %>
      </li>
      <li>
        <%= link_to 'Limpezas', index_limpezas_path %>
      </li>
    </ul>
  </div>
  <!-- /#sidebar-wrapper -->

website/app/views/common/noaccess.html.erb
<%= render 'common/header' %>
</head>
<body>

<%= render 'common/navbar' %>
<div class="container">

  <h1> Não tem permissões para aceder a esta página...</h1>

  <%= link_to 'Voltar atrás', :back %>
</div>

<%= render 'common/footer' %>