website/config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'searchrios#display'
  get 'profile' => 'profile#display'
  get 'home' => 'home#homepage'
  get 'contactos' => 'about#about'
  get 'documentos' => 'documentos_relacionados#documentos'
  get 'distritos' => 'concelho#getDistritos'
  get 'concelhos' => 'concelho#getConcelhosFromDistrito'
  get 'limpeza/new' => 'limpeza#new'
  get 'limpeza/info' => 'limpeza#info'
  get 'limpeza/:id' => 'limpeza#show', :as => :limpeza
  delete 'limpeza/:id' => 'limpeza#destroy'
  get 'respostas' => 'limpeza#getRespostas'

  get 'adminpanel' => 'admin#index' #users index
  get 'adminpanel/form_irrs' => 'admin#form_irrs', :as => :index_form_irrs
  get 'adminpanel/sos_rios' => 'admin#reports', :as => :index_reports
  get 'adminpanel/rotas' => 'admin#rotas', :as => :index_rotas
  get 'adminpanel/trips' => 'admin#trips', :as => :index_trips
  get 'adminpanel/guardarios' => 'admin#guardarios', :as => :index_guardarios
  get "adminpanel/limpezas", :to => 'admin#limpezas', :as => :index_limpezas

  post 'submitProblemasAction' => 'limpeza#submitProblemas'
  post 'changePermissions' => 'users#updatepermissions'

  post 'rota_point_image' => 'rota_point_image#create'
  delete 'rota_point_image/:id' => 'rota_point_image#destroy'

  post 'trip_point_image' => 'trip_image#create'
  delete 'trip_point_image/:id' => 'trip_image#destroy'

  get 'meusguardarios' => 'guardarios#getMine'

  #info pages
  get 'reabilitacao/info' => 'reabilitacaos#info'
  get 'form_irr/info' => 'form_irrs#info'
  get 'report/info' => 'reports#info'
  get 'lab_rios/info' => 'lab_rios#info'
  get 'participacao_publica/info' => 'participacao_publica#info'
  get 'projetos/info' => 'projetos#info'

  #show all
  get 'form_irrs/all' => 'form_irrs#all'
  get 'trips/all' => 'trips#all'

  get 'rio/irrrange' => 'rio#getIRRrange'
  get 'rio/:id' => 'rio#show', as: :rio, :id => /.*/

  get 'form_irrs/img/:caminho' => 'form_irrs#retrieveImage', :caminho => /.*/

  resources :form_irr_image
  resources :reabilitacaos
  resources :guardarios, only: [:index, :show, :new, :create, :destroy]
  resources :reports, only: [:index, :show, :new, :create, :destroy]
  resources :form_irrs
  resources :trip_points
  resources :trips
  resources :routes
  resources :rotas

  patch 'validate_form_irrs/:id' => 'form_irrs#validate', :as => :validate_form_irr
  get 'validate_form_irrs' => 'form_irrs#validate_index'

  devise_for :users, :controllers => {registrations: 'registrations'}

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#homepage'

  # rotas da API, usadas pela app
  namespace :api do
    namespace :v1 do
      resources :problems
      resources :services
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
    end
    namespace :v2 do
      post "/form_irrs", :to => 'form_irrs#create'
      get "/form_irrs", :to => 'form_irrs#getMyForms'
      get "/form_irrs/:id", :to => 'form_irrs#get'
      put "/form_irrs/:id", :to => 'form_irrs#update'
      delete "/form_irrs/:id", :to => 'form_irrs#destroy'

      post "/image", :to => 'image#create'

      post "/guardarios", :to => 'guardarios#create'
      get "/guardarios/:id", :to => 'guardarios#get'
      get "/guardarios", :to => 'guardarios#recent'

      post "/reports", :to => 'reports#create'
      get "/reports", :to => 'reports#index'
      get "/reports/:id", :to => 'reports#get'

      get "/limpezas/:opcao", :to => 'limpezas#getRespostas', :opcao => /.*/
      post "/limpezas", :to => 'limpezas#submitProblemas'

      get "/users", :to => 'users#getUser'
      delete "/users", :to => 'users#destroy'
      put "/users", :to => 'users#update'

	    get "/routes", :to => 'routes#index'
      get "/routes/:id", :to => 'routes#show'

      get "/distritos", :to => 'localidades#getDistritos'
      get "/distritos/:distrito", :to => 'localidades#getConcelhos'
    end
  end

  #web views for app
  get 'rios_mapa_webview' => 'application_web_view#showMapa'
end

website/app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user

  has_many :report_images, dependent: :destroy
  accepts_nested_attributes_for :report_images

  validates :rio, :nome_rio, :lat, :lon, :categoria, :motivo, :descricao, :presence => true

  validates :descricao, length: {maximum: 500}
end

website/app/controllers/api/v2/reports_controller.rb
class Api::V2::ReportsController < ApplicationController
	before_filter :authenticate_user_from_token!

	# POST /reports
	# POST /reports.json
	def create

		user_email = params[:user_email].presence
		user = user_email && User.find_by_email(user_email)

		report = Report.new(report_params)
		report.user_id = user.id

		if report.save
			render :json => {:success => true, :report_id => report.id }
		else
			render :json => '{"success" : "false", "error" : "problem saving report"}'
		end
	end

	# GET /reports/1
	# GET /reports/1.json
	def get
		report = Report.find(params[:id])
		if !report.nil?
			render :json => {:success => "true", :report => report, :images => report.report_images}
		else
			render :json => {:success => "false"}
		end
	end

	# GET /reports
	# GET /reports.json
	def index
		reports = Report.all
		if !reports.nil?
			render :json => {:success => "true", :reports => reports}
		else
			render :json => {:success => "false"}
		end
	end

	def authenticate_user_from_token!
		user_email = params[:user_email].presence
		user = user_email && User.find_by_email(user_email)

		# Notice how we use Devise.secure_compare to compare the token
		# in the database with the token given in the params, mitigating
		# timing attacks.
		if user && Devise.secure_compare(user.authentication_token, params[:user_token])
			user = User.find_by_email(user_email)
			return true
		else
			render :json => '{"success" : "false", "error" : "authentication problem"}'
		end
	end

	private
	def report_params
		params.require(:report).permit(:rio, :nome_rio, :categoria, :motivo, :descricao, :local, :lat, :lon)
	end
end

website/app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!, except: [:info]
  before_action :set_report, only: [:show, :destroy]

  # Mostrar uma página geral de informações sobre denúncias
  def info
    render 'info'
  end

  # GET /reports
  # GET /reports.json
  def index
    @reports = current_user.reports
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @user_reporter = User.find_by_id(@report.user_id)
    @imgs = @report.report_images
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)
    @report.user_id = current_user.id

    respond_to do |format|
      if @report.save
        if params[:images]
          params[:images].each { |image|
            ReportImage.create(image: image, report_id: @report.id)
          }
        end

        #Envia um email a todos os adminsitradores da respectiva denúncia
        UserMailer.reports_email(@report).deliver_now
        format.html { redirect_to @report, notice: 'Denúncia enviada.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Denúncia removida.' }
      format.json { head :no_content }
    end
  end

  private
  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:rio, :nome_rio, :lat, :lon, :categoria, :motivo, :descricao, :local, {images: []})
  end
end

website/app/helpers/reports_helper.rb
module ReportsHelper
end

website/app/views/reports/_form.html.erb
<%= simple_form_for @report, html: { multipart: true } do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">

      <%= f.input :rio, :label => 'Código do rio', :input_html => {:id => 'codigo-rio'}, :readonly => true, :placeholder => 'Clique em cima do rio para selecionar',
          :required => true %>
      <%= f.input :nome_rio, :label => 'Nome do rio', :input_html => {:id => 'nome-rio'}, :readonly => true, :placeholder => 'Clique em cima do rio para selecionar',
                  :required => true, :class => "form-control" %>

      <%= f.hidden_field :lat %>
      <%= f.hidden_field :lon %>


      <div class="form-group <%= field_class(@report, :categoria)%>">
        <%= f.label :categoria, "Categoria", :class => 'control-label' %>
        <%= f.select :categoria, ['Erosão', 'Poluição', 'Acidente', 'Desflorestação', 'Pesca e caça ilegal',
                                  'Cheia', 'Incêndio', 'Vandalismo', 'Presença de espécies exóticas e invasoras'], {:include_blank => 'Selecione uma categoria'},
                     {:required => true, :class => "form-control"} %>
      </div>


      <div class="form-group <%= field_class(@report, :motivo)%>">
        <%= f.label :motivo, "Motivo", :class => 'control-label' %>
        <%= f.select :motivo, ['Preocupado com a situação a nível ambiental',
                               'Preocupado com a situação a nível Pessoal',
                               'Má Vizinhança',
                               'Necessida de informação adicional',
                               'Demora do processo de esclarecimento/resolução'], {:include_blank => 'Selecione o motivo'},
                     {:required => true, :class => "form-control"} %>
      </div>

      <%= f.input :descricao, :label => 'Descrição', :required => true %><br/>

      <div id="reports-imgs">
        <div id="img-filenames"></div>
        <button id="btn-add-img-report" class="btn btn-primary" type="button"> Adicionar imagens </button>
        <%= file_field_tag "images[]", type: :file, multiple: true, accept: 'image/png,image/gif,image/jpeg', style: 'display:none', id: "report-img-input" %>
      </div>
    </div>
    <br>

    <div class="form-actions">
      <%= f.button :submit, 'Denunciar', :class => "btn-danger"  %>
    </div>
<% end %>

website/app/views/reports/index.html.erb
<%= render 'common/header' %>

</head>
<body>
<%= render 'common/navbar' %>
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1> SOS rios - Lista de denúncias <%= link_to 'Nova denúncia', new_report_path, class: 'btn btn-primary' %></h1>

  <div class="table-responsive">
    <table class="table">
      <tr>
        <th>Código rio</th>
        <th>Nº utilizador</th>
        <th>Mostrar</th>
        <th>Apagar</th>
      </tr>

      <% @reports.each do |report| %>
          <tr>
            <td><%= report.rio %></td>
            <td><%= report.user_id %></td>
            <td><%= link_to 'Mostrar', report %></td>
            <td><%= link_to 'Apagar', report, method: :delete, data: {confirm: 'Tem a certeza que pretende apagar?'} %></td>
          </tr>
      <% end %>
    </table>
  </div>
</div>

<%= render 'common/footer' %>

website/app/views/reports/info.html.erb
<%= render 'common/header' %>
</head>
<body>
<%= render 'common/navbar' %>

<div class="container">
  <div class="row">
    <h1>SOS Rios+</h1>
  </div>

  <div class="row">
    <p>O SOS rios pretende juntar a população para junto dos rios e trabalhar em conjunto com os
      municípios para monitorizar e cuidar dos espaços fluviais.</p>
  </div>
  <div class="row">
    <p>Agora qualquer pessoa com a aplicação Rios+ terá a oportunidade de reportar as autoridades
      máximas do município as más práticas e crimes que ocorrem nos rios e ribeiras por onde passam.
      Criando também uma nova consciência ambiental para cuidar do que pertence a todos nós.</p>
  </div>
  <div class="row">
    <p>Ajude-nos a cuidar do seu rio, do nosso rio, do rio de todos nós. E assim podemos fazer a
      diferença atuando sobre o problema e tomando conhecimento do mesmo em tempo real. Alerte as pessoas
      competentes para resolver o problema com apenas uma foto georreferenciada e uma breve descrição,
      esta mensagem enviada por si será recebida no momento pelas pessoas com o poder de decisão disponíveis para o ajudar.</p>
  </div>

</div>

<%= render 'common/footer' %>

website/app/views/reports/new.html.erb
<%= render 'common/header' %>

</head>
<body>
<%= render 'common/navbar' %>

<div class="container">
  <h1> SOS Rios+ </h1>

  <%= render 'mapa/mapa' %>
  <br>
  <%= render 'form' %>

  <%= link_to 'Voltar atrás', reports_path %>

</div>


<%= render 'common/footer' %>

website/app/views/reports/show.html.erb
<%= render 'common/header' %>

</head>
<body>
<%= render 'common/navbar' %>


<div class="container">

  <% if !flash[:notice].blank? %>
      <div id="notice" class="alert alert-success"> <%= notice %> </div>
  <% end %>

  <h1>Relatório SOS Rios+</h1>
  <table class="table table-hover table-striped">
    <tr>
      <th>Código do Rio</th>
      <td><%= @report.rio %></td>
    </tr>
    <tr>
      <th>Data de denúncia</th>
      <td><%=@report.created_at.strftime("%d/%m/%Y - %H:%M")%></td>
    </tr>
    <tr>
      <th>Nº utilizador</th>
      <td><%= @report.user_id %></td>
    </tr>
    <tr>
      <th>Nome do utilizador</th>
      <td><%=@user_reporter.nome%></td>
    </tr>
    <tr>
      <th>Categoria</th>
      <td><%= @report.categoria %></td>
    </tr>
    <tr>
      <th>Motivo</th>
      <td><%= @report.motivo %></td>
    </tr>
    <tr>
      <th>Descrição</th>
      <td><%= @report.descricao %></td>
    </tr>
  </table>

  <h3>Fotografias</h3>
  <% if !@imgs.nil? %>
      <div id="show-form_irr-imgs">
        <div class="row">
          <% @imgs.each do |img| %>
              <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <%= image_tag(img.image, :class => 'img-responsive') %>
              </div>
          <% end %>
        </div>
      </div>
  <% end %>

  <%= link_to 'Voltar atrás', reports_path %>

</div>


<%= render 'common/footer' %>