website/config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'searchrios#display'
  get 'profile' => 'profile#display'
  get 'home' => 'home#homepage'
  get 'contactos' => 'about#about'
  get 'documentos' => 'documentos_relacionados#documentos'
  get 'distritos' => 'concelho#getDistritos'
  get 'concelhos' => 'concelho#getConcelhosFromDistrito'
  get 'limpeza/new' => 'limpeza#new'
  get 'limpeza/info' => 'limpeza#info'
  get 'limpeza/:id' => 'limpeza#show', :as => :limpeza
  delete 'limpeza/:id' => 'limpeza#destroy'
  get 'respostas' => 'limpeza#getRespostas'

  get 'adminpanel' => 'admin#index' #users index
  get 'adminpanel/form_irrs' => 'admin#form_irrs', :as => :index_form_irrs
  get 'adminpanel/sos_rios' => 'admin#reports', :as => :index_reports
  get 'adminpanel/rotas' => 'admin#rotas', :as => :index_rotas
  get 'adminpanel/trips' => 'admin#trips', :as => :index_trips
  get 'adminpanel/guardarios' => 'admin#guardarios', :as => :index_guardarios
  get "adminpanel/limpezas", :to => 'admin#limpezas', :as => :index_limpezas

  post 'submitProblemasAction' => 'limpeza#submitProblemas'
  post 'changePermissions' => 'users#updatepermissions'

  post 'rota_point_image' => 'rota_point_image#create'
  delete 'rota_point_image/:id' => 'rota_point_image#destroy'

  post 'trip_point_image' => 'trip_image#create'
  delete 'trip_point_image/:id' => 'trip_image#destroy'

  get 'meusguardarios' => 'guardarios#getMine'

  #info pages
  get 'reabilitacao/info' => 'reabilitacaos#info'
  get 'form_irr/info' => 'form_irrs#info'
  get 'report/info' => 'reports#info'
  get 'lab_rios/info' => 'lab_rios#info'
  get 'participacao_publica/info' => 'participacao_publica#info'
  get 'projetos/info' => 'projetos#info'

  #show all
  get 'form_irrs/all' => 'form_irrs#all'
  get 'trips/all' => 'trips#all'

  get 'rio/irrrange' => 'rio#getIRRrange'
  get 'rio/:id' => 'rio#show', as: :rio, :id => /.*/

  get 'form_irrs/img/:caminho' => 'form_irrs#retrieveImage', :caminho => /.*/

  resources :form_irr_image
  resources :reabilitacaos
  resources :guardarios, only: [:index, :show, :new, :create, :destroy]
  resources :reports, only: [:index, :show, :new, :create, :destroy]
  resources :form_irrs
  resources :trip_points
  resources :trips
  resources :routes
  resources :rotas

  patch 'validate_form_irrs/:id' => 'form_irrs#validate', :as => :validate_form_irr
  get 'validate_form_irrs' => 'form_irrs#validate_index'

  devise_for :users, :controllers => {registrations: 'registrations'}

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'home#homepage'

  # rotas da API, usadas pela app
  namespace :api do
    namespace :v1 do
      resources :problems
      resources :services
      devise_scope :user do
        post "/sign_in", :to => 'sessions#create'
        post "/sign_up", :to => 'registrations#create'
        delete "/sign_out", :to => 'sessions#destroy'
      end
    end
    namespace :v2 do
      post "/form_irrs", :to => 'form_irrs#create'
      get "/form_irrs", :to => 'form_irrs#getMyForms'
      get "/form_irrs/:id", :to => 'form_irrs#get'
      put "/form_irrs/:id", :to => 'form_irrs#update'
      delete "/form_irrs/:id", :to => 'form_irrs#destroy'

      post "/image", :to => 'image#create'

      post "/guardarios", :to => 'guardarios#create'
      get "/guardarios/:id", :to => 'guardarios#get'
      get "/guardarios", :to => 'guardarios#recent'

      post "/reports", :to => 'reports#create'
      get "/reports", :to => 'reports#index'
      get "/reports/:id", :to => 'reports#get'

      get "/limpezas/:opcao", :to => 'limpezas#getRespostas', :opcao => /.*/
      post "/limpezas", :to => 'limpezas#submitProblemas'

      get "/users", :to => 'users#getUser'
      delete "/users", :to => 'users#destroy'
      put "/users", :to => 'users#update'

	    get "/routes", :to => 'routes#index'
      get "/routes/:id", :to => 'routes#show'

      get "/distritos", :to => 'localidades#getDistritos'
      get "/distritos/:distrito", :to => 'localidades#getConcelhos'
    end
  end

  #web views for app
  get 'rios_mapa_webview' => 'application_web_view#showMapa'
end

website/app/models/guardario.rb
class Guardario < ActiveRecord::Base
  belongs_to :user

  has_many :guardario_images, dependent: :destroy
  accepts_nested_attributes_for :guardario_images

  validates :rio, :nomeRio, :local, :presence => true
end

website/app/controllers/api/v2/guardarios_controller.rb
class Api::V2::GuardariosController < ApplicationController
	before_filter :authenticate_user_from_token!, except: [:get,:recent]

	def create
		user_email = params[:user_email].presence
		user       = user_email && User.find_by_email(user_email)

		guardario = Guardario.new(guardario_params)
		guardario.user_id = user.id

		if guardario.save
			render :json => {:success => true, :guardario_id => guardario.id }
		else
			render :json => '{"success" : "false", "error" : "problem saving guardario"}'
		end
	end

	def get
		guardario = Guardario.find(params[:id])
		if !guardario.nil?
			render :json => {:success => "true", :guardario => guardario, :images => guardario.guardario_images}
		else
			render :json => {:success => "false"}
		end
	end

  def recent
		guardarios_img = GuardarioImage.last(9)

		if !guardarios_img.nil?
			render :json => {:success => "true", :guardarios => guardarios_img}
		else
			render :json => {:success => "false"}
		end

	end

	def authenticate_user_from_token!
		user_email = params[:user_email].presence
		user = user_email && User.find_by_email(user_email)

		# Notice how we use Devise.secure_compare to compare the token
		# in the database with the token given in the params, mitigating
		# timing attacks.
		if user && Devise.secure_compare(user.authentication_token, params[:user_token])
			user = User.find_by_email(user_email)
			return true
		else
			render :json => '{"success" : "false", "error" : "authentication problem"}'
		end
	end

	private
	def guardario_params
		params.require(:guardario).permit(:rio, :nomeRio, :lat, :lon, :local, :voar, :cantar, :parado, :beber, :cacar, :cuidarcrias, :alimentar, :outro)
	end
end

website/app/controllers/guardarios_controller.rb
class GuardariosController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :destroy, :getMine]
  before_action :set_guardario, only: [:show, :destroy]

  # GET /guardarios
  # GET /guardarios.json
  # display last
  def index
    @guardarios_img = GuardarioImage.last(9).reverse
  end

  # Vai buscar à base de dados apenas os rios do utilizador loggado
  def getMine
    @guardarios = current_user.guardarios
    render 'myguardarios'
  end

  # GET /guardarios/1
  # GET /guardarios/1.json
  def show
    @imgs = @guardario.guardario_images
  end

  # GET /guardarios/new
  def new
    @guardario = Guardario.new
  end

  # GET /guardarios/1/edit
  def edit
  end

  # POST /guardarios
  # POST /guardarios.json
  def create
    @guardario = Guardario.new(guardario_params)
    @guardario.user_id = current_user.id

    respond_to do |format|
      if @guardario.save
        if params[:images]
          params[:images].each { |image|
            GuardarioImage.create(image: image, guardario_id: @guardario.id)
          }
        end
        format.html { redirect_to @guardario, notice: 'O seu avistamento foi reportado com sucesso.' }
        format.json { render :show, status: :created, location: @guardario }
      else
        format.html { render :new }
        format.json { render json: @guardario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guardarios/1
  # PATCH/PUT /guardarios/1.json
  def update
    respond_to do |format|
      if @guardario.update(guardario_params)
        if params[:images]
          params[:images].each { |image|
            GuardarioImage.create(image: image, guardario_id: @guardario.id)
          }
        end
        format.html { redirect_to @guardario, notice: 'Guardario was successfully updated.' }
        format.json { render :show, status: :ok, location: @guardario }
      else
        format.html { render :edit }
        format.json { render json: @guardario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guardarios/1
  # DELETE /guardarios/1.json
  def destroy
    @guardario.destroy
    respond_to do |format|
      format.html { redirect_to guardarios_url, notice: 'Guardario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_guardario
    @guardario = Guardario.find(params[:id])
  end

  def guardario_params
    params.require(:guardario).permit(:rio, :nomeRio, :lat, :lon, :local, :voar, :cantar, :parado, :beber, :cacar, :cuidarcrias, :alimentar, :outro, {images: []})
  end
end

website/app/helpers/guardarios_helper.rb
module GuardariosHelper
end

website/app/views/guardarios/_form.html.erb
<%= simple_form_for @guardario, html: { multipart: true } do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%#= f.input :rio, :label => 'Código do rio', :input_html => {:id => 'codigo-rio'}, :readonly => true, :placeholder => "Clique em cima do rio para selecionar", :required => true %>

      <div id="rio-nome" class="rio-info form-inline">
        <div class="row">
          <div class="thumbnail">

            <div class="row">
              <div class="col-md-6 col-xs-12">
                <%= f.label :rio, "Código do rio:" %>
                <%= f.text_field :rio, :id => 'codigo-rio', :class => 'text_field form-control',
                                 :readonly => true, :placeholder => "Clique em cima do rio para selecionar", :required => true %>
              </div>
              <div class="col-md-6 col-xs-12">
                <%= f.label :nomeRio, "Nome do rio:" %>
                <%= f.text_field :nomeRio, :id => 'nome-rio', :class => 'text_field form-control',
                                 :readonly => true, :placeholder => "Clique em cima do rio para selecionar", :required => true %>
              </div>
              <%= f.hidden_field :lat %>
              <%= f.hidden_field :lon %>
            </div>
            <%= render 'mapa/mapa' %>
          </div>
        </div>
      </div>


      <div class="form-group container">

        <%= f.label :local, "Local onde foi observado?" %><br/>
        <div class="row">
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="radio">
              <%= f.radio_button :local, 'arvores', :required => true %>
              <%= f.label :local_arvores, 'Árvores/Ramo' %>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="radio">
              <%= f.radio_button :local, 'pedra', :required => true %>
              <%= f.label :local_pedra, 'Pedra/Rocha' %>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="radio">
              <%= f.radio_button :local, 'solo', :required => true %>
              <%= f.label :local_solo, 'Solo/Margem' %>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="radio">
              <%= f.radio_button :local, 'mergulhar', :required => true %>
              <%= f.label :local_mergulhar, 'A mergulhar' %>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="radio">
              <%= f.radio_button :local, 'ninho', :required => true %>
              <%= f.label :local_ninho, 'Ninho' %>
            </div>
          </div>
        </div>
      </div>

      <hr>

      <div class="form-group container">
        <div class="row">
          <div class="col-md-4 col-sm-6 col-xs-12">
            <%= f.label :voar, 'Estava a voar?' %><br/>
            <%= f.select :voar, ['Pairar', 'Voo picado para mergulhar', 'Mergulhar', 'De passagem'],
                         {:include_blank => 'Não estava a voar'}, :class => 'form-control' %>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <%= f.label :cantar, 'Estava a cantar?' %><br/>
            <%= f.select :cantar, ['Presença', 'Alerta e marcação de território'],
                         {:include_blank => 'Não estava a cantar'}, :class => 'form-control'%>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <%= f.label :alimentar, 'Estava a alimentar-se?' %>
            <%= f.select :alimentar, ['Peixe', 'Libelinha', 'Pequenos insectos'],
                         {:include_blank => 'Não estava a alimentar-se'}, :class => 'form-control' %>
          </div>
        </div>
      </div>

      <hr>

      <div class="form-group container">
        <div class="row">
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="checkbox">
              <%= f.check_box :parado %>
              <%= f.label :parado, 'Estava parado?' %>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="checkbox">
              <%= f.check_box :beber %>
              <%= f.label :beber, 'Estava a beber?' %>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="checkbox">
              <%= f.check_box :cacar %>
              <%= f.label :cacar, 'Estava a caçar?' %>
            </div>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <div class="checkbox">
              <%= f.check_box :cuidarcrias %>
              <%= f.label :cuidarcrias, 'Estava a cuidar das crias?' %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-xs-12">
            <%= f.input :outro, :label => 'Outro comportamento?' %>
          </div>
        </div>

      </div>

      <hr>

      <div class="form-group container">
        <div id="img-filenames"></div>
        <div id="guarda-rios-imgs">
          <button id="btn-add-img-guardarios" class="btn btn-primary" type="button"> Adicionar imagens </button>
          <%= file_field_tag "images[]", type: :file, multiple: true, accept: 'image/png,image/gif,image/jpeg', style: 'display:none', id: "guardarios-img-input" %>
        </div>
      </div>

    </div>
    <br>
    <div class="form-actions">
      <%= f.button :submit, 'Reportar avistamento' %>
    </div>
<% end %>

website/app/views/guardarios/edit.html.erb
<h1>Editing Guardario</h1>

<%= render 'form' %>

<%= link_to 'Show', @guardario %> |
<%= link_to 'Back', guardarios_path %>

website/app/views/guardarios/index.html.erb
<%= render 'common/header' %>
<%= stylesheet_link_tag 'guardarios' %>
</head>
<body>
<%= render 'common/navbar' %>
<div class="container">
  <h1> Lista de avistamentos guarda-rios mais recentes <%= link_to "Novo avistamento", new_guardario_path, class: "btn btn-primary" %></h1>
  <div class="row">
      <% @guardarios_img.each do |img| %>
        <div class="col-lg-4 col-sm-6 col-xs-12">
          <!-- size: 800x600 -->
          <div class="container-item-guarda-rios thumbnail">
            <%= link_to image_tag(img.image, :class => 'img-responsive'), guardario_path(img.guardario_id) %>
          </div>
        </div>
      <% end %>
  </div>
  <%= link_to 'Meus guardarios', 'meusguardarios' %>
</div>

<%= render 'common/footer' %>

website/app/views/guardarios/myguardarios.html.erb
<%= render 'common/header' %>

</head>
<body>
<%= render 'common/navbar' %>
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1> Lista de avistamentos guarda-rios <%= link_to "Novo avistamento", new_guardario_path, class: "btn btn-primary" %></h1>

  <div class="table-responsive">
    <table class="table">
      <tr>
        <th>Código rio</th>
        <th>Data de criação</th>
        <th>Mostrar</th>
        <th>Apagar</th>
      </tr>

      <% @guardarios.each do |guardario| %>
          <tr>
            <td><%= guardario.rio %></td>
            <td><%= guardario.created_at.strftime("%d/%m/%Y - %H:%M") %></td>
            <td><%= link_to 'Mostrar', guardario %></td>
            <td><%= link_to 'Apagar', guardario, method: :delete, data: {confirm: 'Tem a certeza que pretende apagar?'} %></td>
          </tr>
      <% end %>
    </table>
  </div>

</div>

<%= render 'common/footer' %>

website/app/views/guardarios/new.html.erb
<%= render 'common/header' %>

</head>
<body>
<%= render 'common/navbar' %>

<div class="container">

  <h1> Avistamento guarda-rios </h1>

  <!--<div id="rio-nome" class="form-group container">
    <h4>Nome do rio:</h4>
  </div>-->

  <%= render 'form' %>
  </br>
  <%= link_to 'Voltar atrás', guardarios_path %>


</div>


<%= render 'common/footer' %>

website/app/views/guardarios/show.html.erb
<%= render 'common/header' %>

</head>
<body>
<%= render 'common/navbar' %>


<div class="container">

  <% if !flash[:notice].blank? %>
      <div id="notice" class="alert alert-success"> <%= notice %> </div>
  <% else %>
  <% end %>

  <h1>Avistamento de Guarda-Rios</h1>
  <table class="table table-hover table-striped">
    <tr>
      <th>Código do Rio</th>
      <td><%= @guardario.rio %></td>
    </tr>

    <tr>
      <th>Nº de utilizador</th>
      <td><%= @guardario.user_id %></td>
    </tr>

    <tr>
      <th>Local</th>
      <td>
        <% case @guardario.local %>
        <% when 'ninho' %>
            <%= 'Ninho' %>
        <% when 'arvores' %>
            <%= 'Árvores/Ramo' %>
        <% when 'solo' %>
            <%= 'Solo/Margem' %>
        <% when 'mergulhar' %>
            <%= 'A mergulhar' %>
        <% else %>
            <%= 'Pedra/Rocha' %>
        <% end %></td>
    </tr>


    <tr>
      <th>Estava a voar?</th>
      <td>
        <% if @guardario.voar != '' %>
            <%= @guardario.voar %>
        <% else %> Não
        <% end %>
      </td>
    </tr>


    <tr>
      <th>Estava a cantar?</th>
      <td>
        <% if @guardario.cantar != '' %>
            <%= @guardario.cantar %>
        <% else %> Não
        <% end %>
      </td>
    </tr>

    <tr>
      <th>Estava-se a alimentar?</th>
      <td>
        <% if @guardario.alimentar != '' %>
            <%= @guardario.alimentar %>
        <% else %> Não
        <% end %>
      </td>
    </tr>

    <tr>
      <th>Estava parado?</th>
      <td>
        <% if @guardario.parado %> Sim
        <% else %> Não
        <% end %>
      </td>
    </tr>

    <tr>
      <th>Estava a beber?</th>
      <td>
        <% if @guardario.beber %> Sim
        <% else %> Não
        <% end %>
      </td>
    </tr>

    <tr>
      <th>Estava a caçar?</th>
      <td>
        <% if @guardario.cacar %> Sim
        <% else %> Não
        <% end %>
      </td>
    </tr>

    <tr>
      <th>Estava a cuidar de crias?</th>
      <td>
        <% if @guardario.cuidarcrias %> Sim
        <% else %> Não
        <% end %>
      </td>
    </tr>


  </table>


  <% if !@imgs.nil? %>
      <div id="show-form_irr-imgs">
        <div class="row">
          <% @imgs.each do |img| %>
              <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
                <%= link_to image_tag(img.image, :class => 'img-responsive', :alt => "Imagem de guardarios"), "#{img.image}"  %>
              </div>
          <% end %>
        </div>
      </div>
  <% end %>


  <%= link_to 'Voltar atrás', guardarios_path %>

</div>


<%= render 'common/footer' %>
<%= javascript_include_tag 'guardarios' %>